name: Compile Latex and Release PDF  

on:
  push:
    branches:
      - main
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Commit and Push new file         
        run: |
                  git config user.name <qdumont>           
                  git config user.email <quentindum@live.fr>           
                  git add .           
                  git commit -m "add PDF file"           
                  git push
